/**
 * Internal dependencies.
 */
import type { ProjectTimelineItem } from "./types";

const OWNERS = {
  anita: { name: "anita.kumar@example.com", fullName: "Anita Kumar" },
  julian: { name: "julian.andrews@example.com", fullName: "Julian Andrews" },
  jamie: { name: "jamie.oliver@example.com", fullName: "Jamie Oliver" },
  stacy: { name: "stacy.kreed@example.com", fullName: "Stacy Kreed" },
  alice: { name: "alice.johnson@example.com", fullName: "Alice Johnson" },
  raj: { name: "raj.patel@example.com", fullName: "Raj Patel" },
  nina: { name: "nina.schulz@example.com", fullName: "Nina Schulz" },
  omar: { name: "omar.hassan@example.com", fullName: "Omar Hassan" },
};

const WATCHERS = [
  { name: "marcus.thompson@example.com", fullName: "Marcus Thompson" },
  { name: "james.taylor@example.com", fullName: "James Taylor" },
  { name: "evelyn.carter@example.com", fullName: "Evelyn Carter" },
  { name: "priya.nair@example.com", fullName: "Priya Nair" },
  { name: "leo.fischer@example.com", fullName: "Leo Fischer" },
];

const DEFAULT_ITEMS: ProjectTimelineItem[] = [
  // Milestones
  {
    id: "PTI-2026-00001",
    title: "Design system audit",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: true,
    startDate: "2026-04-15",
    plannedEndDate: "2026-05-02",
    actualEndDate: "2026-05-03",
    owner: OWNERS.anita,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00002",
    title: "Component library update",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-05-03",
    plannedEndDate: "2026-05-10",
    owner: OWNERS.julian,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00003",
    title: "Core layout refactor",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-05-12",
    plannedEndDate: "2026-05-23",
    owner: OWNERS.jamie,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00004",
    title: "Accessibility improvements",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-05-24",
    plannedEndDate: "2026-06-06",
    owner: OWNERS.stacy,
    watchers: WATCHERS.slice(1),
  },
  {
    id: "PTI-2026-00005",
    title: "Regression testing & QA sign-off",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-06-07",
    plannedEndDate: "2026-06-20",
    owner: OWNERS.alice,
    watchers: WATCHERS,
  },
  // Touchpoints
  {
    id: "PTI-2026-00006",
    title: "Kickoff alignment (internal)",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-04-17",
    actualEndDate: "2026-04-18",
    owner: OWNERS.jamie,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00007",
    title: "Quarterly CAM Sync",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-05-07",
    actualEndDate: "2026-05-07",
    owner: OWNERS.anita,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00008",
    title: "Timesheet sending",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-04-17",
    actualEndDate: "2026-05-04",
    owner: OWNERS.stacy,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00009",
    title: "Design - engineering reviews",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-05-19",
    owner: OWNERS.julian,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00010",
    title: "Pre-release walkthrough",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-06-19",
    owner: OWNERS.alice,
    watchers: WATCHERS.slice(1),
  },
  // Additional milestones — June / July
  {
    id: "PTI-2026-00011",
    title: "Performance benchmarking",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-06-21",
    plannedEndDate: "2026-07-04",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00012",
    title: "Internationalisation pass",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-07-05",
    plannedEndDate: "2026-07-18",
    owner: OWNERS.nina,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00013",
    title: "Dark mode implementation",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-07-20",
    plannedEndDate: "2026-08-01",
    owner: OWNERS.omar,
    watchers: WATCHERS.slice(2),
  },
  {
    id: "PTI-2026-00014",
    title: "Documentation & changelog",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-08-04",
    plannedEndDate: "2026-08-15",
    owner: OWNERS.stacy,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00015",
    title: "v2.0 public release",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-08-18",
    plannedEndDate: "2026-08-29",
    owner: OWNERS.anita,
    watchers: WATCHERS,
  },
  // Additional touchpoints
  {
    id: "PTI-2026-00016",
    title: "Sprint retrospective #1",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-05-16",
    actualEndDate: "2026-05-16",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00017",
    title: "Stakeholder demo",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-06-05",
    owner: OWNERS.nina,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00018",
    title: "Budget review",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-06-30",
    owner: OWNERS.jamie,
    watchers: WATCHERS.slice(1, 4),
  },
  {
    id: "PTI-2026-00019",
    title: "Sprint retrospective #2",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-07-11",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00020",
    title: "Client sign-off",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-08-28",
    owner: OWNERS.anita,
    watchers: WATCHERS,
  },
  // September / October — wrap-up & next cycle planning
  {
    id: "PTI-2026-00021",
    title: "Post-launch monitoring",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-09-01",
    plannedEndDate: "2026-09-12",
    owner: OWNERS.julian,
    watchers: WATCHERS.slice(0, 4),
  },
  {
    id: "PTI-2026-00022",
    title: "SEO & analytics integration",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-09-14",
    plannedEndDate: "2026-09-25",
    owner: OWNERS.stacy,
    watchers: WATCHERS.slice(2),
  },
  {
    id: "PTI-2026-00023",
    title: "Error-tracking & alerting setup",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-09-28",
    plannedEndDate: "2026-10-09",
    owner: OWNERS.omar,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00024",
    title: "Component deprecation sweep",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-10-12",
    plannedEndDate: "2026-10-23",
    owner: OWNERS.nina,
    watchers: WATCHERS.slice(1, 3),
  },
  {
    id: "PTI-2026-00025",
    title: "v2.1 patch release",
    project: "atlas-ui-stabilisation",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-10-26",
    plannedEndDate: "2026-11-06",
    owner: OWNERS.raj,
    watchers: WATCHERS,
  },
  // Touchpoints — Q3 / Q4
  {
    id: "PTI-2026-00026",
    title: "Sprint retrospective #3",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-09-04",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00027",
    title: "Monthly billing sync",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-09-30",
    owner: OWNERS.stacy,
    watchers: WATCHERS.slice(1, 4),
  },
  {
    id: "PTI-2026-00028",
    title: "Q3 exec review",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-10-02",
    owner: OWNERS.anita,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00029",
    title: "Vendor SLA check",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-10-16",
    owner: OWNERS.omar,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00030",
    title: "Sprint retrospective #4",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-10-30",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00031",
    title: "End-of-year roadmap planning",
    project: "atlas-ui-stabilisation",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-11-06",
    owner: OWNERS.jamie,
    watchers: WATCHERS,
  },
  // A second project — backend-api-overhaul
  {
    id: "PTI-2026-00032",
    title: "API contract definition",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: true,
    startDate: "2026-03-10",
    plannedEndDate: "2026-03-28",
    actualEndDate: "2026-03-27",
    owner: OWNERS.julian,
    watchers: WATCHERS.slice(0, 3),
  },
  {
    id: "PTI-2026-00033",
    title: "Auth service refactor",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: true,
    startDate: "2026-03-30",
    plannedEndDate: "2026-04-17",
    actualEndDate: "2026-04-22",
    owner: OWNERS.omar,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00034",
    title: "Rate-limiting & throttling",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-04-23",
    plannedEndDate: "2026-05-09",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(1),
  },
  {
    id: "PTI-2026-00035",
    title: "GraphQL schema migration",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-05-12",
    plannedEndDate: "2026-05-29",
    owner: OWNERS.nina,
    watchers: WATCHERS.slice(0, 4),
  },
  {
    id: "PTI-2026-00036",
    title: "Load testing & capacity planning",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-06-01",
    plannedEndDate: "2026-06-20",
    owner: OWNERS.julian,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00037",
    title: "Deprecate legacy REST endpoints",
    project: "backend-api-overhaul",
    type: "Milestone",
    isComplete: false,
    startDate: "2026-06-22",
    plannedEndDate: "2026-07-10",
    owner: OWNERS.omar,
    watchers: WATCHERS.slice(2),
  },
  {
    id: "PTI-2026-00038",
    title: "Internal API kickoff",
    project: "backend-api-overhaul",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-03-12",
    actualEndDate: "2026-03-12",
    owner: OWNERS.julian,
    watchers: WATCHERS.slice(0, 2),
  },
  {
    id: "PTI-2026-00039",
    title: "Consumer team sync",
    project: "backend-api-overhaul",
    type: "Touchpoint",
    isComplete: true,
    plannedEndDate: "2026-04-10",
    actualEndDate: "2026-04-11",
    owner: OWNERS.nina,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00040",
    title: "Security audit handoff",
    project: "backend-api-overhaul",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-05-30",
    owner: OWNERS.raj,
    watchers: WATCHERS.slice(1, 4),
  },
  {
    id: "PTI-2026-00041",
    title: "Breaking-change comms to consumers",
    project: "backend-api-overhaul",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-06-15",
    owner: OWNERS.omar,
    watchers: WATCHERS,
  },
  {
    id: "PTI-2026-00042",
    title: "Go-live sign-off",
    project: "backend-api-overhaul",
    type: "Touchpoint",
    isComplete: false,
    plannedEndDate: "2026-07-09",
    owner: OWNERS.julian,
    watchers: WATCHERS,
  },
];

const FAKE_DATA: Record<string, ProjectTimelineItem[]> = {
  "backend-api-overhaul": DEFAULT_ITEMS.filter(
    (i) => i.project === "backend-api-overhaul",
  ),
};

export function getTimelineItems(projectId: string): ProjectTimelineItem[] {
  return FAKE_DATA[projectId] ?? DEFAULT_ITEMS;
}
