/** @type {import("eslint").FlatConfig[]} */
module.exports = [
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        frappe: true,
        __: true,
        repl: true,
        Class: true,
        locals: true,
        cint: true,
        cstr: true,
        cur_frm: true,
        cur_dialog: true,
        cur_page: true,
        cur_list: true,
        cur_tree: true,
        msg_dialog: true,
        is_null: true,
        in_list: true,
        has_words: true,
        validate_email: true,
        open_web_template_values_editor: true,
        validate_name: true,
        validate_phone: true,
        validate_url: true,
        get_number_format: true,
        format_number: true,
        format_currency: true,
        comment_when: true,
        open_url_post: true,
        toTitle: true,
        lstrip: true,
        rstrip: true,
        strip: true,
        strip_html: true,
        replace_all: true,
        flt: true,
        precision: true,
        CREATE: true,
        AMEND: true,
        CANCEL: true,
        copy_dict: true,
        get_number_format_info: true,
        strip_number_groups: true,
        print_table: true,
        Layout: true,
        web_form_settings: true,
        refresh_many: true,
        refresh_field: true,
        toggle_field: true,
        get_field_obj: true,
        get_query_params: true,
        unhide_field: true,
        hide_field: true,
        set_field_options: true,
        getCookie: true,
        getCookies: true,
        get_url_arg: true,
        md5: true,
        $: true,
        jQuery: true
      }
    },
    rules: {
      indent: "off",
      "brace-style": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-useless-escape": "off",
      "space-unary-ops": ["error", { words: true }],
      "linebreak-style": "off",
      quotes: ["off"],
      semi: "off",
      camelcase: "off",
      "no-unused-vars": "error",
      "no-console": ["warn"],
      "no-extra-boolean-cast": ["off"],
      "no-control-regex": ["off"]
    }
  }
];
