/**
 * Internal dependencies.
 */
import type { Project } from "./types";

export const FAKE_PROJECTS: Project[] = [
  {
    id: "atlas-ui-stabilisation",
    name: "Atlas UI Stabilisation",
    riskLevel: "on-track",
    phase: "delivery-prep",
    burnRatePerWeek: 8000,
    costBurnPercent: 45,
    totalBudget: 100000,
    profitMargin: 45,
    startDate: "2025-11-23",
    nextMilestone: "2026-01-14",
    endDate: "2026-02-28",
    projectManager: {
      name: "Ali Smith",
      initials: "AS",
      email: "ali.smith@rtcamp.com",
    },
    leadEngineer: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Atlas Corporation",
    contractEndDate: "2027-02-28",
  },
  {
    id: "nimbus-analytics-enhancement",
    name: "Nimbus Analytics Enhancement",
    riskLevel: "on-track",
    phase: "kick-off",
    burnRatePerWeek: 12000,
    costBurnPercent: 60,
    totalBudget: 250000,
    profitMargin: 45,
    startDate: "2026-01-10",
    nextMilestone: "2026-01-15",
    endDate: "2026-03-05",
    projectManager: {
      name: "Jordan Blake",
      initials: "JB",
      email: "jordan.blake@rtcamp.com",
    },
    leadEngineer: {
      name: "Evelyn Carter",
      initials: "EC",
      email: "evelyn.carter@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Nimbus International",
    contractEndDate: "2026-03-10",
  },
  {
    id: "atlas-mobile-app-checkout-flow-stabilisation",
    name: "Atlas Mobile App Checkout Flow Stabilisation",
    riskLevel: "at-risk",
    phase: "delivery-prep",
    burnRatePerWeek: 10000,
    costBurnPercent: 115,
    totalBudget: 100000,
    profitMargin: 25,
    startDate: "2026-01-11",
    nextMilestone: "2026-01-20",
    endDate: "2026-01-31",
    projectManager: {
      name: "Alex Morgan",
      initials: "AM",
      email: "alex.morgan@rtcamp.com",
    },
    leadEngineer: {
      name: "Marcus Thompson",
      initials: "MT",
      email: "marcus.thompson@rtcamp.com",
    },
    type: "External",
    clientName: "Atlas Corporation",
    contractEndDate: "2026-02-15",
  },
  {
    id: "eclipse-project-management-tool",
    name: "Eclipse Project Management Tool",
    riskLevel: "on-track",
    phase: "development",
    burnRatePerWeek: 5000,
    costBurnPercent: 40,
    totalBudget: 150000,
    profitMargin: 50,
    startDate: "2026-01-15",
    nextMilestone: "2026-01-25",
    endDate: "2026-03-02",
    projectManager: {
      name: "Sofia Lee",
      initials: "SL",
      email: "sofia.lee@rtcamp.com",
    },
    leadEngineer: {
      name: "Chris Johnson",
      initials: "CJ",
      email: "chris.johnson@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Eclipse Solutions",
    contractEndDate: "2026-03-15",
  },
  {
    id: "quantum-data-migration",
    name: "Quantum Data Migration",
    riskLevel: "on-track",
    phase: "launch",
    burnRatePerWeek: 12000,
    costBurnPercent: 55,
    totalBudget: 200000,
    profitMargin: 40,
    startDate: "2025-12-01",
    nextMilestone: "2026-01-28",
    endDate: "2026-03-05",
    projectManager: {
      name: "Liam Brown",
      initials: "LB",
      email: "liam.brown@rtcamp.com",
    },
    leadEngineer: {
      name: "Olivia Davis",
      initials: "OD",
      email: "olivia.davis@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Quantum Tech",
    contractEndDate: "2027-03-10",
  },
  {
    id: "helios-cloud-storage-integration",
    name: "Helios Cloud Storage Integration",
    riskLevel: "on-track",
    phase: "close-out",
    burnRatePerWeek: 17000,
    costBurnPercent: 68,
    totalBudget: 300000,
    profitMargin: 55,
    startDate: "2026-02-01",
    nextMilestone: "2026-02-10",
    endDate: "2026-04-01",
    projectManager: {
      name: "Michael Wilson",
      initials: "MW",
      email: "michael.wilson@rtcamp.com",
    },
    leadEngineer: {
      name: "Marcus Thompson",
      initials: "MT",
      email: "marcus.thompson@rtcamp.com",
    },
    type: "External",
    clientName: "Helios Systems",
    contractEndDate: "2026-04-30",
  },
  {
    id: "venus-ecommerce-platform-upgrade",
    name: "Venus E-commerce Platform Upgrade",
    riskLevel: "caution",
    phase: "close-out",
    burnRatePerWeek: 10000,
    costBurnPercent: 78,
    totalBudget: 80000,
    profitMargin: 45,
    startDate: "2026-02-15",
    nextMilestone: "2026-02-20",
    endDate: "2026-03-28",
    projectManager: {
      name: "Ella Moore",
      initials: "EM",
      email: "ella.moore@rtcamp.com",
    },
    leadEngineer: {
      name: "James Taylor",
      initials: "JT",
      email: "james.taylor@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Venus Retail",
    contractEndDate: "2026-04-15",
  },
  {
    id: "orion-marketing-automation-revamp",
    name: "Orion Marketing Automation Revamp",
    riskLevel: "caution",
    phase: "discovery",
    burnRatePerWeek: 6000,
    costBurnPercent: 82,
    totalBudget: 220000,
    profitMargin: 50,
    startDate: "2026-02-20",
    nextMilestone: "2026-02-25",
    endDate: "2026-04-01",
    projectManager: {
      name: "Noah Anderson",
      initials: "NA",
      email: "noah.anderson@rtcamp.com",
    },
    leadEngineer: {
      name: "Mia Thomas",
      initials: "MT",
      email: "mia.thomas@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Orion Solutions",
    contractEndDate: "2028-04-15",
  },
  {
    id: "nebula-user-experience-overhaul",
    name: "Nebula User Experience Overhaul",
    riskLevel: "on-track",
    phase: "discovery",
    burnRatePerWeek: 12000,
    costBurnPercent: 50,
    totalBudget: 350000,
    profitMargin: 45,
    startDate: "2026-02-22",
    nextMilestone: "2026-02-22",
    endDate: "2026-05-01",
    projectManager: {
      name: "Ava White",
      initials: "AW",
      email: "ava.white@rtcamp.com",
    },
    leadEngineer: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    type: "External",
    clientName: "Nebula Innovations",
    contractEndDate: "2026-05-15",
  },
  {
    id: "atlas-design-system-consolidation",
    name: "Atlas Design System Consolidation",
    riskLevel: "on-track",
    phase: "launch",
    burnRatePerWeek: 10000,
    costBurnPercent: 48,
    totalBudget: 100000,
    profitMargin: 45,
    startDate: "2026-04-10",
    nextMilestone: "2026-05-10",
    endDate: "2026-05-10",
    projectManager: {
      name: "Ali Smith",
      initials: "AS",
      email: "ali.smith@rtcamp.com",
    },
    leadEngineer: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Atlas Corporation",
    contractEndDate: "2026-05-15",
  },
  {
    id: "nimbus-reporting-dashboard-optimisation",
    name: "Nimbus Reporting Dashboard Optimisation",
    riskLevel: "on-track",
    phase: "development",
    burnRatePerWeek: 17000,
    costBurnPercent: 62,
    totalBudget: 250000,
    profitMargin: 45,
    startDate: "2026-05-03",
    nextMilestone: "2026-05-15",
    endDate: "2026-05-15",
    projectManager: {
      name: "Evelyn Carter",
      initials: "EC",
      email: "evelyn.carter@rtcamp.com",
    },
    leadEngineer: {
      name: "Evelyn Carter",
      initials: "EC",
      email: "evelyn.carter@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Nimbus International",
    contractEndDate: "2026-05-22",
  },
  {
    id: "eclipse-resource-planning-module",
    name: "Eclipse Resource Planning Module",
    riskLevel: "at-risk",
    phase: "close-out",
    burnRatePerWeek: 2500,
    costBurnPercent: 125,
    totalBudget: 30000,
    profitMargin: 45,
    startDate: "2026-02-24",
    nextMilestone: "2026-02-27",
    endDate: "2026-05-31",
    projectManager: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    leadEngineer: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    type: "External",
    clientName: "Eclipse Solutions",
    contractEndDate: "2026-05-31",
  },
  {
    id: "quantum-api-performance-tuning",
    name: "Quantum API Performance Tuning",
    riskLevel: "on-track",
    phase: "delivery-prep",
    burnRatePerWeek: 8000,
    costBurnPercent: 45,
    totalBudget: 150000,
    profitMargin: 50,
    startDate: "2026-02-25",
    nextMilestone: "2026-03-01",
    endDate: "2026-05-18",
    projectManager: {
      name: "Chris Johnson",
      initials: "CJ",
      email: "chris.johnson@rtcamp.com",
    },
    leadEngineer: {
      name: "Chris Johnson",
      initials: "CJ",
      email: "chris.johnson@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Quantum Tech",
    contractEndDate: "2027-05-22",
  },
  {
    id: "helios-identity-access-integration",
    name: "Helios Identity & Access Integration",
    riskLevel: "on-track",
    phase: "close-out",
    burnRatePerWeek: 5000,
    costBurnPercent: 38,
    totalBudget: 200000,
    profitMargin: 45,
    startDate: "2026-02-28",
    nextMilestone: "2026-03-03",
    endDate: "2026-05-31",
    projectManager: {
      name: "Olivia Davis",
      initials: "OD",
      email: "olivia.davis@rtcamp.com",
    },
    leadEngineer: {
      name: "Olivia Davis",
      initials: "OD",
      email: "olivia.davis@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Helios Systems",
    contractEndDate: "2026-06-15",
  },
  {
    id: "venus-subscription-billing-revamp",
    name: "Venus Subscription Billing Revamp",
    riskLevel: "on-track",
    phase: "discovery",
    burnRatePerWeek: 12000,
    costBurnPercent: 58,
    totalBudget: 300000,
    profitMargin: 45,
    startDate: "2026-03-01",
    nextMilestone: "2026-03-01",
    endDate: "2026-05-31",
    projectManager: {
      name: "Emma Martinez",
      initials: "EM",
      email: "emma.martinez@rtcamp.com",
    },
    leadEngineer: {
      name: "Emma Martinez",
      initials: "EM",
      email: "emma.martinez@rtcamp.com",
    },
    type: "External",
    clientName: "Venus Retail",
    contractEndDate: "2026-05-31",
  },
  {
    id: "orion-campaign-insights-platform",
    name: "Orion Campaign Insights Platform",
    riskLevel: "caution",
    phase: "discovery",
    burnRatePerWeek: 20000,
    costBurnPercent: 42,
    totalBudget: 80000,
    profitMargin: 30,
    startDate: "2026-03-01",
    nextMilestone: "2026-05-08",
    endDate: "2026-06-01",
    projectManager: {
      name: "James Taylor",
      initials: "JT",
      email: "james.taylor@rtcamp.com",
    },
    leadEngineer: {
      name: "James Taylor",
      initials: "JT",
      email: "james.taylor@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Orion Solutions",
    contractEndDate: "2026-06-22",
  },
  {
    id: "nebula-mobile-navigation-redesign",
    name: "Nebula Mobile Navigation Redesign",
    riskLevel: "on-track",
    phase: "delivery-prep",
    burnRatePerWeek: 12000,
    costBurnPercent: 52,
    totalBudget: 220000,
    profitMargin: 45,
    startDate: "2026-03-04",
    nextMilestone: "2026-03-08",
    endDate: "2026-06-01",
    projectManager: {
      name: "Mia Thomas",
      initials: "MT",
      email: "mia.thomas@rtcamp.com",
    },
    leadEngineer: {
      name: "Mia Thomas",
      initials: "MT",
      email: "mia.thomas@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Nebula Innovations",
    contractEndDate: "2026-06-22",
  },
  {
    id: "atlas-admin-console-modernisation",
    name: "Atlas Admin Console Modernisation",
    riskLevel: "on-track",
    phase: "launch",
    burnRatePerWeek: 15000,
    costBurnPercent: 60,
    totalBudget: 350000,
    profitMargin: 60,
    startDate: "2026-03-05",
    nextMilestone: "2026-03-10",
    endDate: "2026-06-15",
    projectManager: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    leadEngineer: {
      name: "Marcus Thompson",
      initials: "MT",
      email: "marcus.thompson@rtcamp.com",
    },
    type: "Fixed cost",
    clientName: "Atlas Corporation",
    contractEndDate: "2026-06-30",
  },
  {
    id: "nimbus-data-visualisation-upgrade",
    name: "Nimbus Data Visualisation Upgrade",
    riskLevel: "on-track",
    phase: "discovery",
    burnRatePerWeek: 7500,
    costBurnPercent: 48,
    totalBudget: 100000,
    profitMargin: 45,
    startDate: "2026-03-15",
    nextMilestone: "2026-04-10",
    endDate: "2026-06-22",
    projectManager: {
      name: "Ava White",
      initials: "AW",
      email: "ava.white@rtcamp.com",
    },
    leadEngineer: {
      name: "Julian Andrews",
      initials: "JA",
      email: "julian.andrews@rtcamp.com",
    },
    type: "External",
    clientName: "Nimbus International",
    contractEndDate: "2026-07-01",
  },
  {
    id: "eclipse-knowledge-base-migration",
    name: "Eclipse Knowledge Base Migration",
    riskLevel: "on-track",
    phase: "kick-off",
    burnRatePerWeek: 9000,
    costBurnPercent: 35,
    totalBudget: 180000,
    profitMargin: 48,
    startDate: "2026-03-20",
    nextMilestone: "2026-04-05",
    endDate: "2026-07-10",
    projectManager: {
      name: "Sofia Lee",
      initials: "SL",
      email: "sofia.lee@rtcamp.com",
    },
    leadEngineer: {
      name: "Chris Johnson",
      initials: "CJ",
      email: "chris.johnson@rtcamp.com",
    },
    type: "Retainer",
    clientName: "Eclipse Solutions",
    contractEndDate: "2026-08-01",
  },
];
