export const PROJECT_LIST_COLUMNS = [
  { key: "name", label: "Project name", width: "240px" },
  { key: "phase", label: "Phase", width: "160px" },
  { key: "burnRatePerWeek", label: "Burn rate/week", width: "130px" },
  { key: "costBurnPercent", label: "Cost burn", width: "140px" },
  { key: "totalBudget", label: "Total budget", width: "130px" },
  { key: "profitMargin", label: "Profit margin", width: "120px" },
  { key: "startDate", label: "Start date", width: "130px" },
  { key: "nextMilestone", label: "Next milestone", width: "140px" },
  { key: "endDate", label: "End date", width: "120px" },
  { key: "projectManager", label: "Project manager", width: "200px" },
  { key: "leadEngineer", label: "Lead engineer", width: "200px" },
  { key: "type", label: "Project type", width: "120px" },
  { key: "clientName", label: "Client name", width: "180px" },
  { key: "contractEndDate", label: "Contract end date", width: "160px" },
];
