export const PROJECT_LIST_COLUMNS = [
  { key: "name", label: "Project name", width: "240px" },
  { key: "phase", label: "Phase", width: "160px" },
  { key: "burn_rate_per_week", label: "Burn rate/week", width: "130px" },
  { key: "cost_burn_percent", label: "Cost burn", width: "140px" },
  { key: "total_budget", label: "Total budget", width: "130px" },
  { key: "profit_margin", label: "Profit margin", width: "120px" },
  { key: "start_date", label: "Start date", width: "130px" },
  { key: "next_milestone", label: "Next milestone", width: "140px" },
  { key: "end_date", label: "End date", width: "120px" },
  { key: "project_manager", label: "Project manager", width: "200px" },
  { key: "engineering_manager", label: "Lead engineer", width: "200px" },
  { key: "project_type", label: "Project type", width: "120px" },
  { key: "customer_name", label: "Client name", width: "180px" },
  { key: "contract_end_date", label: "Contract end date", width: "160px" },
];
